import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:uqpay_sdk_flutter/src/sheet/qr/qr_encoder.dart';
import 'package:uqpay_sdk_flutter/src/sheet/qr/qr_error_correction.dart';
import 'package:uqpay_sdk_flutter/src/sheet/qr/qr_matrix.dart';

import 'qr_decoder.dart';

/// A fixture generated by an independent, widely deployed ISO/IEC 18004
/// implementation (segno 1.6.6 for full-capacity symbols, python-qrcode
/// 8.2 for symbols containing pad codewords):
/// the exact module matrix it produced for the same payload and
/// parameters.
class _Fixture {
  _Fixture(File file) {
    final lines = file.readAsLinesSync();
    final fields = <String, String>{};
    var matrixStart = 0;
    for (var i = 0; i < lines.length; i++) {
      final line = lines[i];
      if (line == 'matrix=') {
        matrixStart = i + 1;
        break;
      }
      final eq = line.indexOf('=');
      fields[line.substring(0, eq)] = line.substring(eq + 1);
    }
    name = file.uri.pathSegments.last.replaceAll('.txt', '');
    payload = fields['payload']!;
    version = int.parse(fields['version']!);
    mask = int.parse(fields['mask']!);
    forcedMask = fields['forced_mask'] == '-'
        ? null
        : int.parse(fields['forced_mask']!);
    level = UqpayQrErrorCorrection.values.singleWhere(
      (l) => l.name[0].toUpperCase() == fields['error'],
      orElse: () => throw StateError('bad level in $name'),
    );
    matrix = [
      for (final row in lines.sublist(matrixStart))
        if (row.isNotEmpty) [for (final ch in row.split('')) ch == '1'],
    ];
  }

  late final String name;
  late final String payload;
  late final int version;
  late final int mask;
  late final int? forcedMask;
  late final UqpayQrErrorCorrection level;
  late final List<List<bool>> matrix;
}

List<List<bool>> _grid(UqpayQrMatrix m) => [
  for (var y = 0; y < m.moduleCount; y++)
    [for (var x = 0; x < m.moduleCount; x++) m.isDark(x, y)],
];

void main() {
  final fixtures =
      Directory('test/sheet/qr/fixtures')
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.txt'))
          .map(_Fixture.new)
          .toList()
        ..sort((a, b) => a.name.compareTo(b.name));

  test('fixture corpus is present', () {
    // 1 hello world + 1 EMVCo + 15 version sweep + 8 masks + 3 levels.
    expect(fixtures, hasLength(28));
  });

  group('byte-exact agreement with reference matrices', () {
    // The strongest single check: for every fixture the encoder must
    // reproduce, module for module, the matrix produced by an external
    // reference implementation for the same payload, error level and
    // (where forced) mask. The corpus spans versions 1-40, all four
    // levels, all eight masks, both character-count widths, padded and
    // full-capacity payloads, and every distinct block-interleaving
    // regime in the version sweep.
    for (final f in fixtures) {
      test(f.name, () {
        final encoded = UqpayQrEncoder.encode(
          f.payload,
          errorCorrection: f.level,
          maskPattern: f.forcedMask,
        );
        expect(encoded.version, f.version, reason: 'version selection');
        expect(encoded.maskPattern, f.mask, reason: 'mask selection');
        expect(encoded.moduleCount, f.matrix.length);
        final mismatches = <String>[];
        for (var y = 0; y < encoded.moduleCount; y++) {
          for (var x = 0; x < encoded.moduleCount; x++) {
            if (encoded.isDark(x, y) != f.matrix[y][x]) {
              mismatches.add('($x,$y)');
            }
          }
        }
        expect(mismatches, isEmpty, reason: 'modules differing from reference');
      });
    }
  });

  group('independent decoder round-trip', () {
    // The decoder in qr_decoder.dart shares no tables with the encoder
    // (block structure from segno, alignment positions computed
    // algorithmically) and verifies BCH format/version info, zero
    // Reed-Solomon syndromes per block, terminator and pad structure.
    for (final f in fixtures) {
      test('fixture payload ${f.name}', () {
        final encoded = UqpayQrEncoder.encode(
          f.payload,
          errorCorrection: f.level,
          maskPattern: f.forcedMask,
        );
        final decoded = decodeQr(_grid(encoded));
        expect(decoded.text, f.payload);
        expect(decoded.version, encoded.version);
        expect(decoded.mask, encoded.maskPattern);
        expect(decoded.errorLevelBits, f.level.formatBits);
      });
    }

    // Non-fixture payloads: every level, assorted sizes up to the
    // version-40 maximum, and non-ASCII UTF-8.
    final extraPayloads = <String>[
      'A',
      '1234567',
      'https://uqpay.com/pay?intent=pi_123456789',
      'x' * 500,
      'PAYNOW-${'0' * 996}',
      'Ω≈ç√∫ũéあ漢字🙂',
    ];
    for (final level in UqpayQrErrorCorrection.values) {
      for (final payload in extraPayloads) {
        test(
          'level ${level.name}, ${payload.length} chars round-trips',
          () {
            final encoded = UqpayQrEncoder.encode(
              payload,
              errorCorrection: level,
            );
            expect(decodeQr(_grid(encoded)).text, payload);
          },
        );
      }
    }

    test('version 40 at maximum capacity round-trips', () {
      final payload = 'M' * 2331;
      final encoded = UqpayQrEncoder.encode(payload);
      expect(encoded.version, 40);
      expect(decodeQr(_grid(encoded)).text, payload);
    });
  });

  test('HELLO WORLD data codewords match the hand-derived vector', () {
    // Byte mode, version 1-M: mode 0b0100, count 0b00001011 (11), the
    // ASCII bytes of "HELLO WORLD", a 4-bit terminator, then pad
    // codewords 0xEC/0x11 to the 16 data codewords of 1-M. Deriving the
    // nibble stream by hand (spec worked-example style, cf. Thonky's QR
    // tutorial "Data Encoding") gives:
    //   40 B4 84 54 C4 C4 F2 05 74 F5 24 C4 40 EC 11 EC
    final encoded = UqpayQrEncoder.encode('HELLO WORLD');
    expect(encoded.version, 1);
    final decoded = decodeQr(_grid(encoded));
    expect(decoded.dataCodewords, [
      0x40, 0xB4, 0x84, 0x54, 0xC4, 0xC4, 0xF2, 0x05, //
      0x74, 0xF5, 0x24, 0xC4, 0x40, 0xEC, 0x11, 0xEC,
    ]);
  });

  group('version selection boundaries at level M', () {
    test('published byte capacities (ISO Table 7 spot checks)', () {
      expect(UqpayQrEncoder.byteCapacity(1, UqpayQrErrorCorrection.low), 17);
      expect(UqpayQrEncoder.byteCapacity(1, UqpayQrErrorCorrection.medium), 14);
      expect(
        UqpayQrEncoder.byteCapacity(1, UqpayQrErrorCorrection.quartile),
        11,
      );
      expect(UqpayQrEncoder.byteCapacity(1, UqpayQrErrorCorrection.high), 7);
      expect(UqpayQrEncoder.byteCapacity(2, UqpayQrErrorCorrection.medium), 26);
      expect(
        UqpayQrEncoder.byteCapacity(10, UqpayQrErrorCorrection.medium),
        213,
      );
      expect(
        UqpayQrEncoder.byteCapacity(40, UqpayQrErrorCorrection.medium),
        2331,
      );
      expect(UqpayQrEncoder.byteCapacity(40, UqpayQrErrorCorrection.low), 2953);
    });

    test('payload exactly at a capacity stays in that version', () {
      for (final (version, capacity) in [(1, 14), (2, 26), (9, 180)]) {
        final encoded = UqpayQrEncoder.encode('u' * capacity);
        expect(encoded.version, version, reason: 'capacity $capacity');
      }
    });

    test('one byte over a capacity bumps to the next version', () {
      for (final (version, capacity) in [(2, 14), (3, 26), (10, 180)]) {
        final encoded = UqpayQrEncoder.encode('u' * (capacity + 1));
        expect(encoded.version, version, reason: 'capacity $capacity + 1');
      }
    });

    test('the 8->16 bit character-count switch at v9/v10 is handled', () {
      // 180 bytes is the v9-M maximum with an 8-bit count; 181 needs v10,
      // where the count indicator itself grows to 16 bits.
      expect(UqpayQrEncoder.encode('u' * 180).version, 9);
      expect(UqpayQrEncoder.encode('u' * 181).version, 10);
    });

    test('beyond version 40 throws the typed capacity error', () {
      expect(
        () => UqpayQrEncoder.encode('u' * 2332),
        throwsA(
          isA<UqpayQrCapacityError>()
              .having((e) => e.payloadBytes, 'payloadBytes', 2332)
              .having(
                (e) => e.level,
                'level',
                UqpayQrErrorCorrection.medium,
              )
              .having((e) => e.toString(), 'toString', contains('2332')),
        ),
      );
    });

    test('capacity counts UTF-8 bytes, not code units', () {
      // 14 two-byte characters = 28 bytes: past v2-M's 26-byte capacity
      // even though the string has only 14 code points.
      expect(UqpayQrEncoder.encode('é' * 14).version, 3);
    });
  });

  group('masking', () {
    test('all 8 forced masks produce structurally valid symbols', () {
      for (var mask = 0; mask < 8; mask++) {
        final encoded = UqpayQrEncoder.encode(
          'UQPAY MASK CHECK',
          maskPattern: mask,
        );
        expect(encoded.maskPattern, mask);
        // decodeQr validates the format info BCH for the mask and the
        // full symbol structure; a wrong mask formula breaks the
        // syndrome check because the codewords come back garbled.
        final decoded = decodeQr(_grid(encoded));
        expect(decoded.mask, mask);
        expect(decoded.text, 'UQPAY MASK CHECK');
      }
    });

    test('automatic selection picks the documented winner', () {
      // The ISO/IEC 18004 7.8.3 penalty evaluation is deterministic. For the
      // classic "HELLO WORLD" byte-mode 1-M symbol with spec 7.4.10
      // padding this encoder scores mask 4 lowest (total 1103); the pin
      // guards against accidental changes to the penalty rules. (segno
      // picks 2, but for different codewords -- its padding deviation
      // inserts a 0x00 pad byte. Selection
      // agreement with segno is covered by the full-capacity fixtures,
      // where the codewords are identical.)
      expect(UqpayQrEncoder.encode('HELLO WORLD').maskPattern, 4);
    });
  });

  group('determinism and matrix semantics', () {
    test('same input yields an identical matrix across runs', () {
      final a = UqpayQrEncoder.encode('DETERMINISM 123');
      final b = UqpayQrEncoder.encode('DETERMINISM 123');
      expect(a, b);
      expect(a.hashCode, b.hashCode);
    });

    test('quiet zone guidance is the ISO minimum of 4 modules', () {
      expect(UqpayQrMatrix.quietZoneModules, 4);
    });

    test('module count follows 17 + 4 * version', () {
      expect(UqpayQrEncoder.encode('HELLO WORLD').moduleCount, 21);
    });

    test('isDark rejects out-of-range coordinates', () {
      final m = UqpayQrEncoder.encode('HELLO WORLD');
      expect(() => m.isDark(-1, 0), throwsRangeError);
      expect(() => m.isDark(0, 21), throwsRangeError);
    });

    test('toString names version, level and mask, never the payload', () {
      final m = UqpayQrEncoder.encode('SECRET-PAYLOAD');
      expect('$m', contains('version: 1'));
      expect('$m', isNot(contains('SECRET')));
    });
  });

  group('argument validation', () {
    test('empty payload throws ArgumentError', () {
      expect(() => UqpayQrEncoder.encode(''), throwsArgumentError);
    });

    test('out-of-range forced mask throws ArgumentError', () {
      expect(
        () => UqpayQrEncoder.encode('X', maskPattern: 8),
        throwsArgumentError,
      );
      expect(
        () => UqpayQrEncoder.encode('X', maskPattern: -1),
        throwsArgumentError,
      );
    });
  });
}
