#!/usr/bin/env sh
# Writes example/app.env: the ONLY define file the example app is built with.
#
#   example/tool/app_env.sh
#   cd example && flutter run --dart-define-from-file=app.env
#
# It reads example/.env, or else the repo-root .env, and copies exactly three
# app-safe keys into app.env:
#
#   UQPAY_ENVIRONMENT  UQPAY_MERCHANT_BACKEND_URL  UQPAY_ON_BEHALF_OF
#
# Everything else in .env — UQPAY_API_KEY and UQPAY_CLIENT_ID above all —
# belongs to the reference backend only and must never reach the Flutter
# build: every `--dart-define` ends up in generated build files and build
# logs, and a single `String.fromEnvironment` would compile it into the app.
#
# Nothing is echoed: the file is parsed line by line (never sourced, so no
# key is loaded into this shell), values are never printed, and xtrace is off.
set -eu
set +x

example_dir="$(cd "$(dirname "$0")/.." && pwd)"
out="$example_dir/app.env"

src=""
if [ -f "$example_dir/.env" ]; then
  src="$example_dir/.env"
  label="example/.env"
elif [ -f "$example_dir/../.env" ]; then
  src="$example_dir/../.env"
  label="the repo-root .env"
fi
if [ -z "$src" ]; then
  echo "app_env.sh: no .env found (looked in example/.env and the repo root)." >&2
  echo "  cp env.template .env   # from the repo root, then fill it in" >&2
  exit 1
fi

# Prints the value of key $1 from $src: last assignment wins, an optional
# `export ` prefix, surrounding quotes and an unquoted trailing ` # comment`
# are removed, CR is stripped. Prints nothing when the key is absent.
read_key() {
  sed -n "s/^[[:space:]]*\(export[[:space:]][[:space:]]*\)\{0,1\}$1[[:space:]]*=[[:space:]]*//p" "$src" \
    | tail -n 1 \
    | tr -d '\r' \
    | sed -e 's/[[:space:]][[:space:]]*#.*$//' \
          -e 's/[[:space:]]*$//' \
          -e 's/^"\(.*\)"$/\1/' \
          -e "s/^'\(.*\)'\$/\\1/"
}

tmp="$(mktemp "$example_dir/.app.env.XXXXXX")"
trap 'rm -f "$tmp"' EXIT INT TERM

{
  echo "# Generated by example/tool/app_env.sh from $label."
  echo "# App-only defines. Never add UQPAY_API_KEY or UQPAY_CLIENT_ID here."
} >"$tmp"

written=""
for key in UQPAY_ENVIRONMENT UQPAY_MERCHANT_BACKEND_URL UQPAY_ON_BEHALF_OF; do
  value="$(read_key "$key")"
  [ -n "$value" ] || continue
  # A conservative character set: environment names, http(s) URLs and
  # account ids. Anything else is refused (without printing it) so app.env
  # can never carry an extra line or a quoted surprise.
  case "$value" in
    *[!A-Za-z0-9._:/@%+=?\&~-]*)
      echo "app_env.sh: $key in $label has characters this script will not copy; fix it and re-run." >&2
      exit 1
      ;;
  esac
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  written="$written $key"
done

mv "$tmp" "$out"
trap - EXIT INT TERM
echo "app_env.sh: wrote example/app.env with:${written:- (no keys; the app uses its defaults)}"
